Repository BlueMirrors/cvu, pull requests merged in 2022-07, with the labels that each got.

#33 CVU-76 Add gdown for google-drive downloads
  cvu/utils/google_utils.py
  requirements.txt
  setup.py
Labels: enhancement

#26 Update readme
  README.md
Labels: documentation

#34 CVU-80 Fix torch memory and stablization issues
  cvu/detector/yolov5/backends/yolov5_torch.py
Labels: bug

#35 CVU-79 Fix Yolov5-TF-backend issues
  cvu/detector/yolov5/backends/yolov5_tensorflow.py
Labels: bug
