Repository BlueMirrors/cvu, pull requests merged in 2022-08, with the labels that each got.

#38 fix docstring about `agnostic`
  cvu/postprocess/nms/yolov5.py
Labels: documentation

#37 CVU-72: Add ONNX conversion and optional letterbox input-shape arg
  cvu/detector/yolov5/backends/yolov5_onnx.py
  cvu/detector/yolov5/core.py
  cvu/utils/backend_onnx/__init__.py
  cvu/utils/backend_onnx/convert_to_onnx.py
Labels: enhancement

#39 CVU-99 Add "backend_config" to MANIFEST.IN
  MANIFEST.in
Labels: bug
